packages:
  - apps/*
  - packages/*
nodeLinker: hoisted
linkWorkspacePackages: true
preferWorkspacePackages: true
allowBuilds:
  esbuild: true
fetchRetries: 5
fetchTimeout: 600000
networkConcurrency: 8
