import type { AgentSnapshot } from "@qiyun/contracts";

export function demoSnapshot(now = new Date().toISOString()): AgentSnapshot {
  return {
    host: {
      id: "demo-tokyo",
      name: "Tokyo · 生产节点",
      address: "192.0.2.24",
      os: "Ubuntu 24.04 LTS",
      arch: "amd64",
      status: "online",
      cpu: 34,
      memory: 62,
      disk: 41,
      uptime: 1864200,
      lastSeen: now,
      labels: ["演示数据", "Tokyo"],
      history: [22, 30, 26, 38, 33, 42, 34],
    },
    services: [
      {
        id: "demo-blog",
        hostId: "demo-tokyo",
        name: "博客网站",
        kind: "docker",
        category: "website",
        status: "warning",
        state: "running (unhealthy)",
        image: "ghost:5",
        url: "https://blog.example.com",
        port: "2368",
        cpu: 12,
        memory: 28,
        responseMs: 840,
        description: "演示 · 健康检查偶发超时",
        updatedAt: now,
        revision: "demo-blog-v1",
        restartAllowed: true,
      },
      {
        id: "demo-api",
        hostId: "demo-tokyo",
        name: "应用 API",
        kind: "docker",
        category: "application",
        status: "healthy",
        state: "running",
        image: "example/api:1.4",
        port: "3000",
        cpu: 8,
        memory: 19,
        responseMs: 68,
        description: "演示 · 应用接口服务",
        updatedAt: now,
        revision: "demo-api-v1",
        restartAllowed: true,
      },
      {
        id: "demo-postgres",
        hostId: "demo-tokyo",
        name: "PostgreSQL",
        kind: "docker",
        category: "database",
        status: "healthy",
        state: "running",
        image: "postgres:16",
        port: "5432",
        cpu: 5,
        memory: 34,
        description: "演示 · 数据服务（禁止重启）",
        updatedAt: now,
        revision: "demo-db-v1",
        restartAllowed: false,
      },
      {
        id: "demo-nginx",
        hostId: "demo-tokyo",
        name: "Nginx",
        kind: "systemd",
        category: "infrastructure",
        status: "healthy",
        state: "active",
        port: "443",
        cpu: 1,
        memory: 4,
        description: "演示 · 入口代理",
        updatedAt: now,
        revision: "demo-nginx-v1",
        restartAllowed: true,
      },
    ],
    logs: {
      "demo-blog": [
        {
          timestamp: now,
          level: "warn",
          message: "[演示] upstream response exceeded 800ms",
        },
        {
          timestamp: now,
          level: "info",
          message: "[演示] scheduled health check completed",
        },
      ],
      "demo-api": [
        {
          timestamp: now,
          level: "info",
          message: "[演示] GET /health 200 68ms",
        },
      ],
      "demo-postgres": [
        {
          timestamp: now,
          level: "info",
          message: "[演示] checkpoint complete",
        },
      ],
      "demo-nginx": [
        {
          timestamp: now,
          level: "info",
          message: "[演示] configuration syntax is valid",
        },
      ],
    },
  };
}
